services:
  #Aplicação .net
  service.person:
    image: service.person
    container_name: person
    build:
      context: ./Person
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "2195:8080"
    networks:
      - my-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  # Banco de dados PostgreSQL
  postgres:
    image: postgres:14.0
    environment:
      POSTGRES_PASSWORD: pos12345
      POSTGRES_USER: postgres
      POSTGRES_DB: postech
      POSTGRES_ROOT_PASSWORD: root
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5435:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network

  #Servidor de monitoramento Prometheus 
  prometheus:
    build:
      context: ./Prometheus
      dockerfile: Dockerfile
      args:
        version: 1
    image: prometheus-local
    restart: always
    ports:
      - 9090:9090
    networks:
      - my-network
    volumes:
      - './prometheus/data:/data'

  #Serviço do Grafana
  grafana:
    build:
      context: ./Grafana
      dockerfile: Dockerfile
      args:
        version: 1
    image: grafana-local
    restart: always
    ports:
      - 3000:3000
    networks:
      - my-network

networks:
  my-network:
    driver: bridge